branches:
  only:
    - master

language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITHUB_ACCESS_TOKEN}
  keep_history: true
  email: 531578783@qq.com
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master